[package]
name = "rolypoly_bio"
version = "0.1.0"
edition = "2021"

[lib]
name = "rolypoly"
crate-type = ["cdylib"]
path = "src/rolyrs/rolypoly.rs"

[dependencies]
pyo3 = { version = "0.20.3", features = ["extension-module"] }
rand = "0.8.5"
rayon = "1.8.1" 
bio = "1.3"